### ISSUE TITLE
Mutable response parameter

### ISSUE THREAD

**Issue by swizzlr** [bermudadigitalstudio/Titan#45]
Make this possible:
```
app.get("/init") { (req, res) -> (RequestType, ResponseType) in
    res.body = "Hello World"
    return (req, res)
}
```

**Comment by skreutzberger** [comment]
I tried it via `inout` but then the reduce function does not work anymore. Any idea?

```
public typealias Middleware = (inout RequestType, inout ResponseType) -> (RequestType, ResponseType)
```

**Comment by skreutzberger** [comment]
We are coming closer step-by-step I would say. [Here is the WIP feature branch](https://github.com/bermudadigitalstudio/TitanCore/compare/mutable-parameters), currently marked as BROKEN due to some issues with XCTest - please have a look. But maybe it is complete BS and you have a much simpler solution.

**Comment by swizzlr** [comment]
@skreutzberger how about this:

```
app.get("/init") { (req, res) -> Void in
      res.body = "Hello World"
      req.path = "/rewritten"
      res.code = 500
    }
```
